url_target:
  endpoint: https://api.eosargentina.io
  path: /v1/chain/get_info
  response: "200"
eos:
  target:
    name: producer name
    max_time_last_block: 130

log_file: /var/log/gorra.log
t_bot:
  chat_id: "5xxx"
  bot_token: "5xx:x-x_xx"
