url_target:
  endpoint: http://127.0.0.1:8888
  response: "200"
eos:
  target:
    name: oooblockprod
    max_time_last_block: 130
    stand_by: False

log_file: /home/mini/code/notchxor/gorra/gorra.log
t_bot:
  chat_id: "-xxxx"
  bot_token: "5xx:xxxx"
